### ISSUE TITLE
Markdown -> beamer introduces unwanted blank lines before LaTeX environments

### ISSUE THREAD

**Issue by juliangilbey** [jgm/pandoc#1196]
Hi John!

In this markdown file:

```
Text.
\begin{align*}
E&=mc^2
\end{align*}
```

running the command `pandoc -t beamer test.md -o test.tex` (using pandoc 1.12.3.3) results in the LaTeX fragment:

```
\begin{frame}

Text.

\begin{align*}
E&=mc^2
\end{align*}

\end{frame}
```

with an extra blank line between `Text.` and `\begin{align*}`, resulting in unwanted space before the displayed equations.

There might be a good use case for this behaviour, but if so, it would be great to be able to turn it off.

Thanks!

**Comment by mb21** [comment]
This is fixed now.

**Comment by Serenade600** [comment]
Still not work for `subequations` environment. Pandoc 2.12.
Like
```
asdfasdfasdfas
\begin{subequations}
asdf
\end{subequations}
asdfasdfasdfasdf
```
in sub.md is converted to
```
asdfasdfasdfas

\begin{subequations}
asdf
\end{subequations}

asdfasdfasdfasdf

```
in sub.tex.
