### ISSUE TITLE
Inline Verbatim text isn't given a specific style in ODT output

### ISSUE THREAD

**Issue by gareththered** [jgm/pandoc#3390]
If I write \`Pandoc\` inline within a markdown input file, it displays with a different font as `Pandoc` which is fine.  However, that seems to be done by simply changing the font to _Courier New_ for an ODT output file.  
The same input used to create a DOCX file attaches the _Verbatim Char_ character style to the verbatim inline text, which I can control by adjusting this style in my `custom-reference.docx` file I add to the command line options.  
Is there a way to get the ODT output to behave the same.  That is, add a character style to inline verbatim text instead of simply changing the font?  I could then control this style in a `custom-reference.odt` file.

**Comment by Warmduscher** [comment]
Also the font-size of verbatim is fixed to 10pt. This gives arkward results when used inside a header or if used inline inside text blocks using a different font-size.

**Comment by jgm** [comment]
Yes, the opendocument writer is currently fairly primitive.  I didn't write it, and I don't understand the details of the format well enough to change it.  But it would be nice for someone to take this on, replacing all the auto-generated styles with real styles.

**Comment by jtojnar** [comment]
Verified this still happens with `pandoc 3.7.0.2`. If I create a [document](https://github.com/user-attachments/files/25318447/source-test-pandoc.odt) as follows:

```ShellSession
$ pandoc -f markdown -o source-test-pandoc.odt
# Test `foo`

Hello `world`
```

it will contain:

### `content.xml`

```xml
<text:h text:style-name="Heading_20_1" text:outline-level="1">
  <text:bookmark-start text:name="test-foo" />Test
  <text:span text:style-name="Source_Text">foo</text:span>
  <text:bookmark-end text:name="test-foo" />
</text:h>
<text:p text:style-name="First_20_paragraph">Hello
  <text:span text:style-name="Source_Text">world</text:span>
</text:p>
```

### `styles.xml`

```xml
<style:style style:family="text" style:name="Source_Text">
      <style:text-properties style:font-name="Courier New" style:font-name-asian="Courier New" style:font-name-complex="Courier New" style:font-size-asian="10pt" style:font-size-complex="10pt" fo:font-size="10pt" fo:language="zxx" />
</style:style>
```

---

Creating a [document in LibreOffice Writer](https://github.com/user-attachments/files/25318427/source-text.odt) and using the built-in _Source Text_ character style will produce:


### `content.xml`

```xml
<text:h text:style-name="Heading_20_1" text:outline-level="1">Test
	<text:span text:style-name="Source_20_Text">
		<text:span text:style-name="T1">foo</text:span>
	</text:span>
</text:h>
<text:p text:style-name="P1">Hello
	<text:span text:style-name="Source_20_Text">world</text:span>
</text:p>
```

### `styles.xml`

```xml
<style:style style:name="Source_20_Text" style:display-name="Source Text" style:family="text">
	<style:text-properties style:font-name="Liberation Mono" fo:font-family="&apos;Liberation Mono&apos;" style:font-family-generic="modern" style:font-pitch="fixed" style:font-name-asian="Liberation Mono" style:font-family-asian="&apos;Liberation Mono&apos;" style:font-family-generic-asian="modern" style:font-pitch-asian="fixed" style:font-name-complex="Liberation Mono" style:font-family-complex="&apos;Liberation Mono&apos;" style:font-family-generic-complex="modern" style:font-pitch-complex="fixed"/>
</style:style>
```

----

So actually, there is a style (introduced in 13bc573e7f9e0602404dd37fec2c7cd14b5c56ee) but not one recognised by LibreOffice UI.

Corresponding reader issue: https://github.com/jgm/pandoc/issues/4841

**Edit:** I started implementing both of these.
