### ISSUE TITLE
reveal.js slideNumber cannot be set to non-bool from yaml metadata block

### ISSUE THREAD

**Issue by azrdev** [jgm/pandoc#3753]
This is pandoc 1.19.2.1 from Archlinux (binary) package, reveal.js is at 43eada7.

Build a slide show for reveal.js with markdown source. According to [the documentation](https://github.com/hakimel/reveal.js#slide-number), it's possible to turn `slideNumber`s on with `true`, and to configure them using a string syntax. You can pass this syntax to the pandoc command:
~~~sh
pandoc -V slideNumber=\"c/t\" -s -t revealjs
~~~
but I think it's more elegant to set this in the YAML metadata block, however
~~~yaml
slideNumber: "c/t"
~~~
will strip the quotes, creating invalid javascript. And inserting escaped quotes like
~~~yaml
slideNumber: "\"c/t\""
~~~
yields them escaped in javascript, too:
~~~javascript
slideNumber: &quot;c/t&quot;,
~~~

-----

Maybe #2276 was the same thing.

**Comment by jgm** [comment]
#3537 should fix this: you'll be able to say
```
slideNumber: `"c/t"`{=html}
```
and it will be interpreted as raw content when rendering HTML (i.e. the " will not be escaped).

**Comment by maurerle** [comment]
Hello @jgm , this didnt fix it for raw html in the toml header:

Pandoc version: 2.11.4
I get this message and a html file which contains the raw toml part with the slides following

```
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'presentation' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```

presentation.md:
```
---
title: Test
author: User
theme: beige
slideNumber: `c/t`{=html}
---

# Sample

1. Just a test
```

Command: pandoc -s -t revealjs presentation.md > test.html

**Comment by jgm** [comment]
This isn't valid YAML (note: it's YAML not TOML here).
You need single quotes
```
slideNumber: '`c/t`{=html}'
```
or
```
slideNumber: |
   `"c\t"`{=html}
```
Because of the invalid YAML, pandoc is treating this as a table rather than YAML metadata.

**Comment by maurerle** [comment]
Yes, thank you! 
This helped:
```
slideNumber: '`"c/t"`{=html}'
```
This:
```
slideNumber: |
   `"c\t"`{=html}
```
created a new paragraph around the option.

I think this is worth mentioning in the docs too :smile:
