### ISSUE TITLE
--pdf-engine full path of the engine not working

### ISSUE THREAD

**Issue by priiduonu** [jgm/pandoc#4681]
According to the documentation:

`--pdf-engine=pdflatex|lualatex|xelatex|wkhtmltopdf|weasyprint|prince|context|pdfroff`

If the engine is not in your PATH, the full path of the engine may be specified here.
```
pandoc README.md -o out.pdf --pdf-engine=/usr/bin/xelatex
pdf-engine /usr/bin/xelatex not known
```
without full path it works:

```
pandoc README.md -o out.pdf --pdf-engine=xelatex
```
pandoc version used:
```
pandoc -v
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
```
It was working (with and without full path) in version 1.19.1
`/usr/bin/xelatex` exists and is executable.

**Comment by mb21** [comment]
Indeed, was this bug introduced in https://github.com/jgm/pandoc/commit/582cb4b505b774fe8b7424363bcf310e97871c53 ?

**Comment by mb21** [comment]
Indeed, I believe this was introduces by https://github.com/jgm/pandoc/commit/582cb4b505b774fe8b7424363bcf310e97871c53, specifically the deletion of `takeBaseName`...

**Comment by gandalfsaxe** [comment]
I'm also having this issue.

`pandoc --pdf-engine=L:\portable\miktex-portable-2.9.6753\texmfs\install\miktex\bin
\pdflatex.exe test.tex -o test.pdf`

Gives me:

`pdf-engine L:\portable\miktex-portable-2.9.6753\texmfs\install\miktex\bin\pdflatex.exe not known`

However just launching `L:\portable\miktex-portable-2.9.6753\texmfs\install\miktex\bin\pdflatex.exe` works fine. Any suggestions?

**Comment by gandalfsaxe** [comment]
Could be because the fix is not in latest release (2.2.1) yet?

**Comment by jgm** [comment]
Correct.  This is fixed in HEAD, but not in  a release.

**Comment by pciavald** [comment]
I'm still having the issue with pandoc 2.3.1 on macOS 10.13 with spaces in paths.

not working : 
```
$ pandoc --pdf-engine=/Users/user/Library/Application\ Support/app/xelatex
$ pandoc --pdf-engine="/Users/user/Library/Application Support/app/xelatex"
```

working : 
```
$ pandoc --pdf-engine=/Users/user/Desktop/xelatex
$ /Users/user/Library/Application\ Support/app/xelatex
```

**Comment by jgm** [comment]
Try

    --pdf-engine="/Users/user/Library/Application\ Support/app/xelatex"

**Comment by pciavald** [comment]
I've just tried that again, it does not work. I noticed that adding `"` around the path makes the engine unrecognizable by pandoc (`pdf-engine must be one of ...`), so for instance
```
$ pandoc --pdf-engine="/Users/user/Desktop/xelatex"
```
doesn't work either, while it works without quotes.

**Comment by mb21** [comment]
@pciavald what pandoc version are you on? works for me on pandoc 2.3

**Comment by pciavald** [comment]
My bad, my path problem is actually not lying in pandoc but in nodejs' child_process.spawn which did not handle arguments as I expected, and also seemingly a problem in XeTeX. If anyone comes here experiencing a problem to spawn pandoc with a full-path pdf engine, this did it the trick for me : 

```
let child = spawn(`"${pandoc}"`, [
            `"${contentPath}"`,
            `--output="${outputPath}"`,
            `--template="${headerPath}"`,
            `--pdf-engine="${pdfEngine}"`,
          ], { shell: true })
```
the **shell: true** option launches pandoc with `sh -c '"path/to/pandoc" "path/to/content.md" --output="path/to/output.pdf" --pdf-engine="path/to/engine"'` instead of separating arguments and somewhat changing the quotes / escape sequences.

I'm building a text editor around pandoc, everything works on linux but on Mac it's a bit more complex seemingly due to spaces in paths. In [this log](https://pastebin.com/FGLWGz89) you can see that pandoc successfully launches XeLaTeX but there's a path problem somewhere, accessing the "Application Support" folder : 

```
sh: /Users/pciavald/Library/Application: No such file or directory
sh: /Users/pciavald/Library/Application: No such file or directory
Error producing PDF.
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex 2018.10.12)  12 OCT 2018 22:25
```

Here's [the TeXLive installation profile](https://pastebin.com/QRaYmqMM) used, where we can see that paths have a space. I tried `"/quoting/the path/"` but it ends up installing `"path/to the/folder"/resource` and I tried escaping the paths without quotes and it results in `/creating\\\ wrong/folders`.

[Trying XeTeX standalone](https://pastebin.com/tJXwDJZS) also does not work with the same error, which confirms pandoc is not the cause. If you have any idea why this may be happening, i'd be glad to hear. Tried IRC freenode#latex without luck. Sorry for wrong issue digging, and thank you for maintaining Pandoc it's a wonderful tool.

**Comment by jgm** [comment]
@pciavald you may need to both double-quote and escape spaces:
```
--output="/path/with\ spaces/myfile\ with\ spaces.txt"
```

**Comment by archonic** [comment]
Is this fix still unreleased? I'm running pandoc 2.7.2 and getting `pdf-engine must be one of wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, tectonic, pdfroff, context` when specifying a valid path.

**Comment by wizpresso-steve-cy-fan** [comment]
Please reopen this issue, which is exist in the following version:
```
pandoc.exe 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: C:\Users\SteveFan\AppData\Roaming\pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by wizpresso-steve-cy-fan** [comment]
This issue happens if you want to use MikTex in Windows, but they renamed everything to have `miktex-` prefix, but it is not accepted

**Comment by tarleb** [comment]
@wizpresso-steve-cy-fan that should best go into a separate issue. Please open a new one for this.
